services:
  - name: database
    type: pserv
    plan: free
    image: postgres:latest
    envVars:
      - key: POSTGRES_DB
        value: land_draft_db
      - key: POSTGRES_USER
        value: user
      - key: POSTGRES_PASSWORD
        generateValue: true

  - name: backend
    type: web
    plan: free
    env: python
    repo: https://github.com/MSTakeshi/20250813-land-draft-app-deploy.git
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: database
          property: connectionString

  - name: frontend
    type: web
    plan: free
    env: node
    repo: https://github.com/MSTakeshi/20250813-land-draft-app-deploy.git
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: backend
          property: url